# Generated by Django 5.1.2 on 2024-12-09 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_board_file_name_board_file_path_comment"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="comment",
        ),
    ]
