# Generated by Django 5.1.2 on 2024-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_comment_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="comment",
            field=models.IntegerField(default=0),
        ),
    ]
