# Generated by Django 5.1.2 on 2024-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_board_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.IntegerField(),
        ),
    ]
